### ISSUE TITLE
Exception with latest build

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#1009]
When running the latest build on some of our files, I got the following exception:

```
SHFB: Error BE0065: BUILD FAILED: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sandcastle.Core.PresentationStyle.StandardApiTocGenerator.AddNamespaceOrTypeTopic(XmlWriter writer, String memberId)
   at Sandcastle.Core.PresentationStyle.StandardApiTocGenerator.AddNamespaceOrTypeTopic(XmlWriter writer, String memberId)
   at Sandcastle.Core.PresentationStyle.StandardApiTocGenerator.GenerateApiTocFile(String reflectionDataFile, String tocFile)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```
I can send you the files and project if you want.

**Comment by RobertvanderHulst** [comment]
[test.zip](https://github.com/EWSoftware/SHFB/files/12024855/test.zip)
This is the project that causes the crash

**Comment by EWSoftware** [comment]
You're using the XPath Reflection Filter to remove API members.  When removing them, you also need to remove the corresponding element members from the API members that appear in namespaces and types.  For example:

```
/reflection/apis/api/elements/element[contains(@api,"XSharp.ADS.ACE")]
```
