### ISSUE TITLE
Error BE0065: BUILD FAILED: 'IsConfigurable' property specified was not found.

### ISSUE THREAD

**Issue by payal7patel** [EWSoftware/SHFB#1019]
SHFB: Error BE0065: BUILD FAILED: 'IsConfigurable' property specified was not found.
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExportDefinitions()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.DiscoverExportsAndImports()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExports()
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitionsInternal()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String contractName)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(ImportDefinition definition)
   at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore[T,TMetadataView](String contractName)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

'IsConfigurable' property specified was not found.
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)

**Comment by EWSoftware** [comment]
It's likely finding an older copy of the SHFB assemblies somewhere.  Check the log to see what paths it searching for components.

**Comment by payal7patel** [comment]
How to fix the issue. I didn't have this issue before

**Comment by EWSoftware** [comment]
If you are using any build components or plug-ins in your documentation project, make sure they are up to date and compatible with the latest release.  Check the Components and Plug-Ins categories in the project properties to find out if any are used.  The paths searched for components are listed at the start of the build log.  Even if you aren't using any, it will still search those paths for components and may be finding something that is older.  Removing any out-of-date components from the search folders should resolve the issue.

If you are using the SHFB NuGet package in your documentation project, make sure it is up to date as well.

**Comment by payal7patel** [comment]
Yes there was XSD plugin installed from old version which is not compatible in new version.
Thanks for your help.
Now I have different issue.
There is no xml comments being added into help file.

Here is the warning I got
CopyFromIndexComponent: No index entry found for key ''.
SHFB: Warning BE0066: ShowMissingComponent: [T:ProjectName] Missing <summary> documentation
SHFB: Warning BE0066: ShowMissingComponent: [T:ProjectName] Missing <remarks> documentation
