### ISSUE TITLE
Using plugin XPath Reflection File Filter leads into BE0065 error

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#1031]
For a special kind of documentation I'm no longer able to compile it. I get the following error:

```
Applying document model to reflection output...
Removing items matching '/reflection/apis/api[contains(@id,"#ctor")]'
    Removed 49 items
Removing items matching '/reflection/apis/api[attributes/attribute[type/@api='T:System.Runtime.InteropServices.ComVisibleAttribute']/argument/value = 'False']'
    Removed 52 items
Removing items matching '/reflection/apis/api/elements/element[@source = 'extension']'
    Removed 0 items
Removing items matching '/reflection/apis/api[memberdata/@static='true']'
    Removed 79 items
    Last step completed in 00:00:00,1110
-------------------------------

SHFB: Error BE0065: BUILD FAILED: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sandcastle.Core.PresentationStyle.StandardDocumentModel.UpdateGeneralApiNode(ApiMember memberNode)
   at Sandcastle.Core.PresentationStyle.StandardDocumentModel.ApplyDocumentModel(String reflectionDataFile, String docModelReflectionDataFile)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

Last documentation with that filter entries was done with an SHFB in 2019.

**Comment by VBWebprofi** [comment]
I think I have an idea why it happens. I remove the class in case of the XPath excludes as `api` element but not from the element list in the namespace:

![image](https://github.com/EWSoftware/SHFB/assets/10100623/d639742c-3852-48f0-8313-3a3850a37ac4)

How do I XPath select the `Class2` in namespace `elements` when it has not a related `api` entry?

**Comment by EWSoftware** [comment]
Sorry, I'm not clear on what it is you're actually trying to do.
