### ISSUE TITLE
With .NET 8 SDK, `BinaryFormatter` seems to be disallowed, resulting in some plugin failures

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#1035]
I got `SHFB : error BE0065: BUILD FAILED: An unexpected error occurred while attempting to create the build component 'Switch
Component'` as an error while building a doc project.

Looking in the log, it has:

```
SHFB: Error BE0065: BUILD FAILED: An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponents(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.AddComponents(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot, Thread threadPoolThread)

One or more errors occurred. (An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponents(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.AddComponents(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot, Thread threadPoolThread)

An unexpected error occurred while attempting to create the build component &#39;Resolve Reference Links Component&#39;
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponents(XPathNavigator configuration)
   at Sandcastle.Tools.BuildComponents.SwitchComponent.Initialize(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)

BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Sandcastle.Tools.BuildComponents.ResolveReferenceLinksComponent.CreateMemberIdResolver(XPathNavigator configuration)
   at Sandcastle.Tools.BuildComponents.ResolveReferenceLinksComponent.Initialize(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)
```

Based on the contents of the obj folder at that time, I'm assuming it's the GenRefInfo cache files that trigger this?

I could have sworn this has worked before, and I tried cleaning all intermediate and output folders in case it was some stray file getting in the way, but that did not help.

**Comment by Zastai** [comment]
Strangely I'm getting an error with the .NET SDK 6.0.25 too (which does not disable `BinaryFormatter`), but there the root exception is different:

```
Attempting to deserialize an empty stream.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Sandcastle.Tools.BuildComponents.ResolveReferenceLinksComponent.CreateMemberIdResolver(XPathNavigator configuration)
   at Sandcastle.Tools.BuildComponents.ResolveReferenceLinksComponent.Initialize(XPathNavigator configuration)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.LoadComponent(XPathNavigator configuration)
```

**Comment by EWSoftware** [comment]
I'm aware of the issue.  The cache used to contain resolved reference links is stored in a binary format.  I've found a way to generate the links without the web service thus removing the need for the cache altogether.  It may be a few weeks before I get it done and release an update though.

**Comment by Zastai** [comment]
Any idea on what the second issue (empty stream) could be?

I am running into that on every attempt to build any SHFB project, even with `msbuild.exe` (which uses .NET Framework, so no `BinaryFormatter` issue).
Even with the (now very old) SHFB version we're using in CI:

```
  BuildAssembler (v2020.3.6.0)
  Copyright c 2006-2020, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2020, Eric Woodruff, All Rights Reserved.
  Loading configuration...
BuildAssembler : error :  [C:\path\to\project\output\Release\Website\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Resolve Reference Links Component&#39;. The error message is: Attempting to deserialize an empty stream. [C:\path\to\project\output\Release\Website\BuildTopics.proj]
BuildAssembler : error :  [C:\path\to\project\output\Release\Website\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Multi-format Output Component&#39;. The error message is: See log for details [C:\path\to\project\output\Release\Website\BuildTopics.proj]
BuildAssembler : error :  [C:\path\to\project\output\Release\Website\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;. The error message is: See log for details [C:\path\to\project\output\Release\Website\BuildTopics.proj]
Done Building Project &quot;C:\path\to\project\output\Release\Website\BuildTopics.proj&quot; (default targets) -- FAILED.
```

Unfortunately, there's no logging (even with -v:d) that would indicate what stream it's trying to read (a file? a url?).

It does seem specific to my machine at the moment (a colleague using the same VS2022 version and .NET 8SDK installed is able to build without error), making it even weirder. I did try clearing my temporary files folder as well as my nuget cache in case there was an issue there, with no change.

**Comment by EWSoftware** [comment]
The URL cache file might be corrupted.  Delete the %USERPROFILE%\Local Settings\Application Data\EWSoftware\Sandcastle Help File Builder\Cache folder and it will rebuild it.

**Comment by Zastai** [comment]
That was it, thanks. Is there a way to inhibit that file's use, or configure its location, from the project file?

I'm not sure I like the idea that a single broken file can break all builds on a machine; that could significantly disrupt CI/CD.

**Comment by Zastai** [comment]
Note that I'm now getting:

```
BuildAssembler : warning : ResolveReferenceLinksComponent: ... Member ID URL resolver service failed.  No further look ups will be performed for this build. [...\BuildTopics.proj]
BuildAssembler : warning : Reason: The remote server returned an error: (403) Forbidden. [...\BuildTopics.proj]
```

**Comment by Zastai** [comment]
@EWSoftware Hi. Do you have a rough idea of when a release could be published (including the 8.0.0 version of SHFB.NET)?

**Comment by EWSoftware** [comment]
My free time has been rather limited of late.  I'm going to try again this weekend to get it published.  I've got Monday off so should be able to get it out.

**Comment by EWSoftware** [comment]
Version 2024.2.18.0 is now available along with the updated reflection data set packages.

**Comment by Zastai** [comment]
Awesome! Thanks a lot.

**Comment by Zastai** [comment]
Note: it looks like this file remains available (and presumably up to date): https://learn.microsoft.com/en-us/dotnet/.xrefmap.json

I wonder if it makes sense to add a test (even if it's an ignored one intended for manual runs only) that gets that file and then verifies that the new in-code resolver handles the mapping correctly?
