### ISSUE TITLE
Cannot install extension on arm64

### ISSUE THREAD

**Issue by scegg** [EWSoftware/SHFB#1045]
When trying install SHFB on arm64 Visual Studio 2022, after SHFB main program installed, the extension cannot be installed:
This extension is not installable on any currently installed products.

<img width="991" alt="image" src="https://github.com/EWSoftware/SHFB/assets/3340557/179d76ca-215c-4ec6-85f5-ecc7a7c044e4">

```
2/19/2024 8:16:51 PM - Microsoft VSIX Installer
2/19/2024 8:16:51 PM - -------------------------------------------
2/19/2024 8:16:51 PM - vsixinstaller.exe version:
2/19/2024 8:16:51 PM - 17.9.3174+fce230bb0d
2/19/2024 8:16:51 PM - -------------------------------------------
2/19/2024 8:16:51 PM - Command line parameters:
2/19/2024 8:16:51 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\allen\AppData\Local\Temp\_tc0\InstallResources\SHFBVisualStudioPackage_VS2022AndLater.vsix
2/19/2024 8:16:51 PM - -------------------------------------------
2/19/2024 8:16:51 PM - Microsoft VSIX Installer
2/19/2024 8:16:51 PM - -------------------------------------------
2/19/2024 8:16:52 PM - Initializing Install...
2/19/2024 8:16:52 PM - Searching for applicable products...
2/19/2024 8:16:53 PM - Found installed product - Visual Studio Enterprise 2022
2/19/2024 8:16:54 PM - Found installed product - Global Location
2/19/2024 8:16:54 PM - Extension Details...
2/19/2024 8:16:54 PM - 	Identifier         : SHFB.A8C96335-DAF7-4D30-89E2-B004400E4525
2/19/2024 8:16:54 PM - 	Name               : SHFB (VS2022 and Later)
2/19/2024 8:16:54 PM - 	Author             : EWSoftware
2/19/2024 8:16:54 PM - 	Version            : 2024.2.18.0
2/19/2024 8:16:54 PM - 	Description        : Visual Studio integration for the Sandcastle Help File Builder.
2/19/2024 8:16:54 PM - 	Locale             : en-US
2/19/2024 8:16:54 PM - 	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
2/19/2024 8:16:54 PM - 	InstalledByMSI     : False
2/19/2024 8:16:54 PM - 	SupportedFrameworkVersionRange : [4.7,)
2/19/2024 8:16:54 PM - 	SignatureState     : Unsigned
2/19/2024 8:16:54 PM - 	Supported Products : 
2/19/2024 8:16:54 PM - 		Microsoft.VisualStudio.Community
2/19/2024 8:16:54 PM - 			Version : [17.0,18.0)
2/19/2024 8:16:54 PM - 			ProductArchitecture : amd64
2/19/2024 8:16:54 PM - 	References         : 
2/19/2024 8:16:54 PM - 	Prerequisites      : 
2/19/2024 8:16:54 PM - 		-------------------------------------------------------
2/19/2024 8:16:54 PM - 		Identifier   : Microsoft.Component.MSBuild
2/19/2024 8:16:54 PM - 		Name         : MSBuild
2/19/2024 8:16:54 PM - 		Version      : [16.0,)
2/19/2024 8:16:54 PM - 		-------------------------------------------------------
2/19/2024 8:16:54 PM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
2/19/2024 8:16:54 PM - 		Name         : .NET desktop development tools
2/19/2024 8:16:54 PM - 		Version      : [17.0,)
2/19/2024 8:16:54 PM - Signature Details...
2/19/2024 8:16:54 PM - 	Extension is not signed.
2/19/2024 8:16:54 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by PaulStSmith** [comment]
I came to report the same.
But my configuration is:

```
Device name	Enterprise
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
Installed RAM	16.0 GB
Device ID	29146F36-5DB3-4FBC-A45F-00157DCEE9B6
Product ID	00331-10000-00001-AA665
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎22.‎Nov.‎2024
OS build	19045.5198
Experience	Windows Feature Experience Pack 1000.19060.1000.0
```

# Error log:
```
Microsoft VSIX Installer
-------------------------------------------
vsixinstaller.exe version:
17.12.2069+1ec5133e4b
-------------------------------------------
Command line parameters:
C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\pauls\AppData\Local\Temp\Rar$EXa14004.47503.rartemp\InstallResources\SHFBVisualStudioPackage_VS2017And2019.vsix
-------------------------------------------
Microsoft VSIX Installer
-------------------------------------------
Skipping product Microsoft.VisualStudio.Product.BuildTools (d4008aaf) since it does not support extensions
Initializing Install...
Searching for applicable products...
Found installed product - Visual Studio Community 2022
Found installed product - Global Location
Extension Details...
	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
	Name               : SHFB (VS2017 and VS2019)
	Author             : EWSoftware
	Version            : 2024.9.12.0
	Description        : Visual Studio integration for the Sandcastle Help File Builder.
	Locale             : en-US
	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
	InstalledByMSI     : False
	SupportedFrameworkVersionRange : [4.5,)
	SignatureState     : Unsigned
	Supported Products : 
		Microsoft.VisualStudio.Community
			Version : [15.0,17.0)
			ProductArchitecture : x86
	References         : 
	Prerequisites      : 
		-------------------------------------------------------
		Identifier   : Microsoft.Component.MSBuild
		Name         : MSBuild
		Version      : [15.0,)
		-------------------------------------------------------
		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
		Name         : .NET desktop development tools
		Version      : [15.0,)
Signature Details...
	Extension is not signed.
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by PaulStSmith** [comment]
A workaround I found was to install through Chocolatey.

```
choco install sandcastle
```

**Comment by EWSoftware** [comment]
@PaulStSmith  Your VSIX error log indicates that you tried to install the VS2017 and VS2019 version but it didn't find either.  You need to install the VS2022 version of the VSIX file which is separate.  Note that the sandcastle tools (MSBuild support) are installed via MSI.  The VSIX is just for Visual Studio integration.  If you're installing the tools manually, you'll find the MSI and VSIX installers in the .\InstallResources folder assuming you downloaded the guided installer from this project site.

**Comment by PaulStSmith** [comment]
That is true. 
But I simply ran the installer. Next. Next. Next. 
And the installer didn't select the 2022.

**Comment by EWSoftware** [comment]
It's been known to happen usually related to an old version of the build tools being installed that get detected as an installed version of Visual Studio.  Running it manually works around it.
