### ISSUE TITLE
Build error SHE0002 when building CHM with huge HTML files

### ISSUE THREAD

**Issue by ChetanRaiyani-CPR** [EWSoftware/SHFB#1087]
**SHFB version : 2024.9.12.0
Target binaries : .NET 8** 

When building CHM file with huge HTML files(4000+), it gives SHE0002 build errors.
This is very generic error, So can not solve this error. 
Checked Folder read-only property etc, but can not solve this error with anything.

**Please refer attachment.**
(Due to confidential info, I have hide some information in image)
![SHFB_BuildError](https://github.com/user-attachments/assets/110f4739-8a16-4e7d-a917-4dc71c2c919b)

**Build error :**
SHFB: Error SHE0002: Unexpected error during title and keyword HTML extract
   at SandcastleBuilder.Utils.BuildEngine.TitleAndKeywordHtmlExtract.ExtractHtmlInfo()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at SandcastleBuilder.Utils.BuildEngine.TitleAndKeywordHtmlExtract.ParseFiles(String fileFolder, String localizedOutputFolder)
   at SandcastleBuilder.Utils.BuildEngine.TitleAndKeywordHtmlExtract.ExtractHtmlInfo()

Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.TitleAndKeywordHtmlExtract.ProcessFile(String basePath, String sourceFile, String localizedOutputFolder)
   at SandcastleBuilder.Utils.BuildEngine.TitleAndKeywordHtmlExtract.<>c__DisplayClass35_0.<ParseFiles>b__0(String file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

**Note :**
SHFB version : 2022.2.6.0
in this version, CHM generation is successfully carried out. though it gives another problem.
Problem :  Microsoft API's link does not appear in built CHM.
Please refer attached image for this issue : 
(Due to confidential info, I have hide some information in image)
![MSLinkMissing](https://github.com/user-attachments/assets/1a39fcee-f845-4f35-bcf2-217cb5ea1330)

**Comment by EWSoftware** [comment]
It's probably trying to report a warning when processing the HTML files in parallel.  It should be fixed for the next release.  Version 2022.2.6.0 uses an older link resolver but Microsoft has since shut those services down so it won't resolve links to online topics anymore.

**Comment by ChetanRaiyani-CPR** [comment]
Thank you @EWSoftware 
I will check latest release(2024.12.15)
