### ISSUE TITLE
Generating Markdown gives Error BE0019

### ISSUE THREAD

**Issue by Eonasdan** [EWSoftware/SHFB#113]
I'm trying to build Markdown files for a class library and I keep getting this error message.

I've been able to build a chm file without trouble.

```
SHFB: Error BE0019: Unable to transform template 'GenerateMarkdownContent.proj': Object reference not set to an instance of an object.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.TransformTemplate(String template, String sourceFolder, String destFolder)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
Object reference not set to an instance of an object.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.OnFieldMatch(Match match)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.TransformTemplate(String template, String sourceFolder, String destFolder)
```

do you need the complete build log?

**Comment by EWSoftware** [comment]
I need an example that duplicates the problem.  Can you e-mail me one?  My e-mail address is in the footer of the pages in the help file.

**Comment by Eonasdan** [comment]
I've got it hosted on github: https://github.com/Eonasdan/MomentSharp

You should just be able to download and build it.

**Comment by EWSoftware** [comment]
I was able to duplicate this with the latest production release.  It's actually fixed indirectly through some other changes I've been making for the next release.  In the meantime, you can enable the Root Namespace Container property or add a content layout file with a single topic.  That will allow it to find a default topic and work around the crash.

**Comment by Eonasdan** [comment]
I see you made commit since this issue. Has this been resolved?

**Comment by EWSoftware** [comment]
Yes, though be aware that if you choose to build it from the source, I've made a number of significant changes, some of them that may be breaking with regard to third-party plug-ins and components, that are not yet documented.  The help file isn't up to date yet either regarding said changes.
