### ISSUE TITLE
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by jrowling** [EWSoftware/SHFB#160]
The following code block results in the error log shown below.
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace SandcastleTest
{
    /// <summary>
    /// Organisation additional data service<br/>
    /// This allows optional populating of organisation images
    /// </summary>
    public class OrganisationAdditionalDataService : AdditionalDataServiceBase<Organisation>,
        IAdditionalDataService<Organisation, Organisation>
    {
        private readonly IDatabase _db;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganisationAdditionalDataService"/> class.
        /// </summary>
        /// <param name="db">The database.</param>
        public OrganisationAdditionalDataService(IDatabase db)
        {
            _db = db;
        }

        /// <summary>
        /// Populates the additional data.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="properties">The properties.</param>
        /// <returns></returns>
        public override Organisation PopulateAdditionalData(Organisation model,
            params Expression<Func<Organisation, object>>[] properties)
        {
            foreach (var property in properties)
            {
                var propertyName = property.GetPropertyName();

                // Populate 'Image One'
                if (propertyName == ((Expression<Func<Organisation, byte[]>>) (m => m.ImageOne)).GetPropertyName())
                    model.ImageOne =
                        _db.ExecuteScalar<byte[]>("SELECT orga_image_one FROM ORGANISATION WHERE orga_id = @0",
                            model.OrganisationId);

                // Populate 'Image Two'
                if (propertyName == ((Expression<Func<Organisation, byte[]>>) (m => m.ImageTwo)).GetPropertyName())
                    model.ImageTwo =
                        _db.ExecuteScalar<byte[]>("SELECT orga_image_two FROM ORGANISATION WHERE orga_id = @0",
                            model.OrganisationId);
            }

            return model;
        }
    }

// interface 
   
 /// <summary>
    /// Interface for additional data service
    /// </summary>
    /// <typeparam name="TResult">The type of the result.</typeparam>
    /// <typeparam name="TModel">The type of the model.</typeparam>
    public interface IAdditionalDataService<TResult, TModel>
    {
        /// <summary>
        /// Populates the additional data.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="properties">The properties.</param>
        /// <returns></returns>
        TResult PopulateAdditionalData(TResult model, params Expression<Func<TModel, object>>[] properties);
    }

    /// <summary>
    /// Interface for additional data service
    /// </summary>
    /// <typeparam name="TModel">The type of the model.</typeparam>
    public interface IAdditionalDataService<TModel> : IAdditionalDataService<TModel, TModel>
    {    }

    /// <summary>
    /// Additional data service base class.  
    /// </summary>
    /// <typeparam name="TModel">The type of the model.</typeparam>
    public abstract class AdditionalDataServiceBase<TModel>
    {
        /// <summary>
        /// Populates the additional data.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="properties">The properties.</param>
        /// <returns></returns>
        public abstract TModel PopulateAdditionalData(TModel model, params Expression<Func<TModel, object>>[] properties);

        /// <summary>
        /// Populates the additional data.
        /// </summary>
        /// <param name="models">The models.</param>
        /// <param name="properties">The properties.</param>
        /// <returns></returns>
        public IEnumerable<TModel> PopulateAdditionalData(IEnumerable<TModel> models, params Expression<Func<TModel, object>>[] properties)
        {
            return models.Select(model => PopulateAdditionalData(model));
        }
    }
}
```
Sandcastle Help File Builder error log:
```XML
<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2015.7.25.0" projectFile="C:\Test\SandcastleTest\Documentation1\Documentation1.shfbproj" started="11/08/2015 10:24:54 AM">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\&#39;
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    C:\Test\SandcastleTest\Documentation1
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Framework reflection data location: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework
Using presentation style &#39;VS2013&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013&#39;
Loading and initializing plug-ins...
Lightweight Website Style Version 2015.7.25.0
Copyright &#169; 2006-2015, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
</buildStep>
<buildStep step="ClearWorkFolder">
Clearing working folder...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: C:\Test\SandcastleTest\SandcastleTest\SandcastleTest.csproj
    Found project &#39;C:\Test\SandcastleTest\SandcastleTest\SandcastleTest.csproj&#39;

Parsing project files
    Found assembly &#39;C:\Test\SandcastleTest\SandcastleTest\bin\Debug\SandcastleTest.dll&#39;

References to include (excluding framework assemblies):
    None
SHFB: Warning BE0062: No XML comments files found.  The help file will not contain any member comments.
</buildStep>
<buildStep step="GenerateSharedContent">
Generating shared content files (en-US, English (United States))...
<plugIn name="Lightweight Website Style" behavior="After" priority="1000">
</plugIn>    Last step completed in 00:00:00.0156
</buildStep>
<buildStep step="GenerateApiFilter">
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00.0156
</buildStep>
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\MSBuild\12.0\bin\MSBuild.exe - GenerateRefInfo.proj]
Build started 11/08/2015 10:24:56 AM.
Project &quot;C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj&quot; on node 1 (default targets).
PrepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
GenerateRefInfo:
  MRefBuilder (v2015.7.25.0)
  Copyright c 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2015, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.ArgumentNullException: Value cannot be null. [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error : Parameter name: source [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.GetTemplateParameterPositions(TypeNode declaringType, String name) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.ParametersMatch(ParameterList parameters1, ParameterList parameters2, Boolean noMatchOnGenericVersions) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.GetTemplateMember(Member member) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteTypeElements(TypeNode type) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteType(TypeNode type) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespace(Namespace space) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespace(Namespace space) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj]
Done Building Project &quot;C:\Test\SandcastleTest\Documentation1\Help\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:00.32
    Last step completed in 00:00:00.4375
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
```

**Comment by EWSoftware** [comment]
Your example is missing some key classes needed to build it.  Just stubbing them in doesn't duplicate the issue either.  Can you e-mail me a buildable example that fails?  My e-mail address is in the footer of the pages in the help file.

**Comment by EWSoftware** [comment]
I can't duplicate the null reference exception using the example you sent.  However, it did generate the same "No members in the template matched the parameters of the specialization" error as reported in issues #154.  I've already fixed that and, when using the fixed version, it doesn't generate that error anymore.  It's possible they're related and that fixes covers this one too.

I'll probably release a patched version of MRefBuilder for issue #154.  Once I do, you can try it and see if it resolves your problem as well.

**Comment by jrowling** [comment]
Excellent.  Look forward to the patch for #154, and will advise. Thanks.

**Comment by EWSoftware** [comment]
I've attached a patched version of MRefBuilder.exe to the release page (https://github.com/EWSoftware/SHFB/releases/tag/v2015.7.25.0).  Extract it and replace the installed version of MRefBuilder.exe with it and see if it fixes the issue.

**Comment by jrowling** [comment]
Thanks – will give it a spin now.

**Comment by jrowling** [comment]
That has the isolated failed test now working.  Now to run it in the larger project.  Great work, thanks.
