### ISSUE TITLE
XAML Desgner breaks in Visual Studio 2015 when/SHFB extension is enabled

### ISSUE THREAD

**Issue by FuntechBlins** [EWSoftware/SHFB#193]
This seems to consistently happen mainly in type library projects (not WPF/exe projects) that contain XAML Windows or UserControls. The XAML designer view throws with the exception/trace I pasted below. Note that if I disable the SHFB extension and restart Visual Studio then the XAML designer works fine again in the same project(s).

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.DesignTools.DesignerHost.Platform.DTEReferenceResolver.GetReferences(IHostProject project, Object& connectionPointSource)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProject.GetReferenceResolver(IServiceProvider serviceProvider, HostProject project)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProject.GetReferences()
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProject.InitializeInternal()
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProject.Initialize()
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProjectService.<>c__DisplayClass75_0.<GetHostProject>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.Invoke(Boolean waitingInExternalCall)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.InvokeCall(Call call)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.DirectInvoke(Boolean inbound, Action action, Int32 sourceApartmentId, Int32 targetApartmentId, Int32 originId, WaitHandle aborted)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.DirectInvokeInbound(Action action, Int32 targetApartmentId)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalIn(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallSynchronizationMode syncMode, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn(IRemoteObject targetObject, Action action, CallSynchronizationMode syncMode, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProjectService.GetHostProject(IVsHierarchy hierarchy, Boolean create)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProjectService.FindApplicationProject(String projectPath)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProjectService.<FindProjectsInternal>d__114.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostProjectService.FindProject(FindProjectCriteria criteria, String criteriaValue)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteHostProjectService.<>c__DisplayClass29_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostProjectService.FindProject>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass46_0`1.<MarshalIn>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.

Server stack trace: 
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalInSynchronous(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalIn(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallSynchronizationMode syncMode, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn(IRemoteObject targetObject, Action action, CallSynchronizationMode syncMode, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn[TResult](IRemoteObject targetObject, Func`1 func, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteHostProjectService.Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostProjectService.FindProject(FindProjectCriteria criteria, String criteriaValue)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteHostProjectService.FindProject(FindProjectCriteria criteria, String criteriaValue)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalHostProjectService.<>c__DisplayClass45_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.IHostProjectService.FindProject>b__0(IRemoteHostProjectService ps)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass30_0`2.<MarshalOut>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOutSynchronous(Action action, Int32 targetApartmentId, WaitHandle aborted, WaitHandle timeoutSignal, CancellationToken cancelToken, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOut(Action action, Int32 targetApartmentId, WaitHandle aborted, CancellationToken cancelToken, CallSynchronizationMode syncMode, WaitHandle timeoutSignal, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TValue](RemoteHandle`1 targetObject, Action action, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TResult,TValue](RemoteHandle`1 targetObject, Func`2 func, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalHostProjectService.Microsoft.VisualStudio.DesignTools.DesignerContract.IHostProjectService.FindProject(FindProjectCriteria criteria, String criteriaValue)
   at Microsoft.VisualStudio.DesignTools.Designer.Project.ProjectContextManager.FindApplicationProjectContext(IProjectContext requestingContext)
   at Microsoft.VisualStudio.DesignTools.XamlDesigner.DocumentModel.XamlProjectContext.get_Application()
   at Microsoft.VisualStudio.DesignTools.Designer.Documents.SceneDocument.GetApplicationDocument(IProjectContext activeContext)
   at Microsoft.VisualStudio.DesignTools.Designer.View.ViewRootResolver.GetView(IDocumentRoot documentRoot, Boolean hidden)
   at Microsoft.VisualStudio.DesignTools.Designer.DocumentViewContext.CreateAndOpenViewInternal(SceneDocument document, CancellationToken cancelToken, Boolean activate, Boolean ensureOpenInHost)
   at Microsoft.VisualStudio.DesignTools.Designer.DesignerService.CreateDesigner(IHostSourceItem item, IHostTextEditor editor, CancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteDesignerService.<>c__DisplayClass12_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteDesignerService.CreateDesigner>b__0(CancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteDesignerService.<>c__DisplayClass6_0`1.<MarshalInWithCancellation>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.

Server stack trace: 
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalInSynchronous(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalIn(Action action, Int32 targetApartmentId, CancellationToken cancelToken, CallSynchronizationMode syncMode, CallModality callModality, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalIn(IRemoteObject targetObject, Action action, CancellationToken cancelToken, CallSynchronizationMode syncMode, CallModality callModality, ApartmentState apartmentState, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteDesignerService.MarshalInWithCancellation[TResult](IRemoteCancellationToken remoteToken, Func`2 func, ApartmentState apartmentState)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.RemoteDesignerService.Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteDesignerService.CreateDesigner(IRemoteHostProject remoteProject, IRemoteHostSourceItem remoteItem, IRemoteHostTextEditor remoteEditor, IRemoteCancellationToken remoteToken)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.IRemoteDesignerService.CreateDesigner(IRemoteHostProject remoteProject, IRemoteHostSourceItem remoteItem, IRemoteHostTextEditor remoteEditor, IRemoteCancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalDesignerService.CreateDesignerImpl(IRemoteDesignerService ds, IHostSourceItem item, IHostTextEditor editor, RemoteCancellationToken remoteCancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalDesignerService.<>c__DisplayClass14_0.<Microsoft.VisualStudio.DesignTools.DesignerContract.IDesignerService.CreateDesigner>b__0(IRemoteDesignerService ds, RemoteCancellationToken remoteToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalDesignerService.<>c__DisplayClass5_0`1.<MarshalOutWithCancellation>b__0(IRemoteDesignerService ds)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.<>c__DisplayClass27_0`1.<MarshalOut>b__0()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.Call.InvokeWorker()

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.WaitForCompletion(NestedCallContext nestedCallContext, BlockingCall call, WaitHandle timeoutSignal)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOutSynchronous(Action action, Int32 targetApartmentId, WaitHandle aborted, WaitHandle timeoutSignal, CancellationToken cancelToken, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.STAMarshaler.MarshalOut(Action action, Int32 targetApartmentId, WaitHandle aborted, CancellationToken cancelToken, CallSynchronizationMode syncMode, WaitHandle timeoutSignal, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TValue](RemoteHandle`1 targetObject, Action action, CancellationToken cancelToken, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.ThreadMarshaler.MarshalOut[TValue](RemoteHandle`1 targetObject, Action`1 action, CancellationToken cancelToken, CallSynchronizationMode syncMode, ApartmentState apartmentState, String methodName, String filePath, Int32 lineNumber)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalDesignerService.MarshalOutWithCancellation[TResult](CancellationToken cancelToken, Func`3 func, ApartmentState apartmentState)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Remoting.LocalDesignerService.Microsoft.VisualStudio.DesignTools.DesignerContract.IDesignerService.CreateDesigner(IHostSourceItem item, IHostTextEditor editor, CancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.IsolatedDesignerService.IsolatedDesignerView.CreateDesignerViewInfo(CancellationToken cancelToken)

**Comment by EWSoftware** [comment]
I'm not able to duplicate this issue.  SHFB does not extend nor interact with the WPF designer in any way so it seems doubtful that SHFB would cause an issue.  You can try uninstalling the SHFB package and reinstalling it.

**Comment by FuntechBlins** [comment]
Thanks, I understand not being able to repro may make this issue dead in the water. I was doubting it myself before I even posted the issue and I already did try repairing Visual Studio (no luck), the only thing that makes the error subside is unloading the extension and restarting Visual Studio at which point it is completely gone. If I load the extension again, the error comes back the next time I go to view a XAML page. The exception manifests itself similar to the one reported below event though the trace is different and I am in a C# type library project...

https://connect.microsoft.com/VisualStudio/feedback/details/1616056/nullreferenceexception-when-launching-xaml-designer-on-c-blank-app-template

**Comment by EWSoftware** [comment]
Does this happen if you create a brand new WPF user control library project and add a SHFB project?  If not, perhaps it's something unique to your WPF project.

**Comment by nitrix78** [comment]
For information, I meet the same problem.

**Comment by schikla** [comment]
I have the opposite problem. When I change the target framework of my project from 4.5.x to 4.0, the xaml designer crashes. If I go back to 4.5.x all is fine. After uninstalling the VS extension "SHFB" v2015.10.10.0 no more crashes occur.

**Comment by EWSoftware** [comment]
Keeping the SHFB project separate from the WPF project rather than in the same solution or making sure the WPF designer is opened at least once before interacting with the SHFB project have been reported as workarounds.

**Comment by AutomationML** [comment]
I had the same issue with a sandcastle project in the solution. Removing the sandcastle project solves the problem

**Comment by Christoph142** [comment]
I do have the same issue. Thanks for mentioning the workaround. Removing the Sandcastle project from the solution makes the designer work again indeed. This should be fixed, though.

**Comment by anat0li** [comment]
I do have the same issue as many others.  EWSoftware closing this with "CannotRepro" label looks funny because the issue is easy to reproduce. For instance, just open the solution for [Tom's Toolbox](https://github.com/tom-englert/TomsToolbox) project . You can see every xaml designer broken with the same   System.NullReferenceException thrown. Uninstalling SHFB fixes everything. I think some other label type should be used for the closing, such as  "don't wanna repro".

**Comment by EWSoftware** [comment]
@anat0li:  If you can reproduce it, feel free to diagnose and fix the issue.  This is an open source project after all.  If not, the workarounds are noted above.

**Comment by anat0li** [comment]
@EWSoftware: IMHO who does the research & fix on the bug is a separate question. For community project it can be virtually anybody who has time and desire to go through all that code forest. The bug can easily stay open until that happens. But what could be the reason to close some existing critical problem, totally killing all projects around in the solution? Do you think marking the bug with "CannotRepo" gives other people a reason to invest time in discrediting that conclusion?

**Comment by omaerkhan** [comment]
I have the same issue. I'm running Visual Studio 2015 Pro, and have a solution with a WPF project (.Net 4.5.2), and an SHFB project (SHFB extension version: 2016.5.28.0).
My WPF designer works occasionally, and then randomly crashes with the same Null Reference Exception as the OP.
After I "unloaded" the SHFB project, the designer started working without any issues. I find that "Unloading" the project as a temporary workaround is easier than temporarily removing the SHFB project from the solution.

**Comment by EWSoftware** [comment]
Apparently it's no longer an issue with the latest release so try upgrading to it (v2016.9.17.0).
