### ISSUE TITLE
Generating markdown

### ISSUE THREAD

**Issue by simonmurdock** [EWSoftware/SHFB#213]
Any project I've tried to generate has this problem:

SHFB: Error BE0019: Unable to transform template 'GenerateMarkdownContent.proj': Object reference not set to an instance of an object.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.TransformTemplate(String template, String sourceFolder, String destFolder)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
Object reference not set to an instance of an object.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.OnFieldMatch(Match match)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.TransformTemplate(String template, String sourceFolder, String destFolder)

Any ideas?

I searched the issue history and am currently using the root element workaround, but can provide a DLL privately if you need.

**Comment by EWSoftware** [comment]
Are you using the latest release.  As far as I know, that issue was fixed.

**Comment by simonmurdock** [comment]
You're right. Latest version fixed it.
