### ISSUE TITLE
Error thrown when using both "Additional Content Only" and "Assembly Binding Redirection" plug-ins

### ISSUE THREAD

**Issue by swirlywonder** [EWSoftware/SHFB#314]
I discovered an extremely minor issue during plugin development and testing. If the "Additional Content Only" plug-in is enabled on a project using "Assembly Binding Redirection", the following error will be thrown:

Unexpected error while executing plug-in 'Assembly Binding Redirection': System.IO.FileNotFoundException: Could not find file '...\Working\MRefBuilder.config'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at SandcastleBuilder.PlugIns.BindingRedirectResolverPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecuteBeforeStepPlugIns()
   at SandcastleBuilder.PlugIns.AdditionalContentOnlyPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)

**Comment by EWSoftware** [comment]
Assembly binding redirection serves no purpose with the Additional Content Only plug-in since it suppresses generation of reflection data and the configuration file it relies on.  The obvious solution here is to not use the binding redirection plug-in with the Additional Content only plug-in.

**Comment by swirlywonder** [comment]
I would agree with you, however the reason it came up in my case was when I used it to temporarily disable assembly documentation for a quick check of the conceptual content. This is inline with the intended use of the plug-in per it's description here:

> This plug-in can be used to build a help file consisting of nothing but conceptual content and/or additional content items. _It is also useful for proofreading your conceptual and/or additional content without having to build all the API topics._

I had recalled reading that in the past so I wanted to bring that scenario to your attention.
