### ISSUE TITLE
Memory Access Violation

### ISSUE THREAD

**Issue by PluginIO** [EWSoftware/SHFB#318]
**[EDIT]
Since installing your tools then restarting Visual Studio, even if I create a new solution and project, I get 0 warnings and 0 errors but the project fails to build. :/
[END EDIT]**

When attempting to build a Sandcastle project with VS2015, MSBuild.exe causes an access violation error. I have attempted with multiple Framework versions, 4.0 and 4.5, given MSBuild elevated permissions, tried multiple documentation type configurations and I don't believe that this is a memory corruption issue. 

## Visual Studio Information
![image](https://cloud.githubusercontent.com/assets/1716106/16895834/1d855ccc-4bab-11e6-917f-0acd74fc201a.png)

## System Information
![image](https://cloud.githubusercontent.com/assets/1716106/16895843/5ad6bb98-4bab-11e6-93e2-2d81047db31a.png)

## IDE Overview
![image](https://cloud.githubusercontent.com/assets/1716106/16895818/b41bb0ec-4baa-11e6-83b2-13e0873d4965.png)

## Contents of LastBuild.log
`<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2016.5.28.0" projectFile="C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation\Documentation.shfbproj" started="7/16/2016 11:06:40 PM">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\&#39;
Locating components in the following folder(s):
    C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Using framework reflection data for &#39;.NET Framework 4.5&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework&#39;
Using presentation style &#39;VS2013&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013&#39;
Loading and initializing plug-ins...
Assembly Binding Redirection Version 2016.5.28.0
Copyright &#169; 2006-2016, Eric Woodruff, All Rights Reserved
Lightweight Website Style Version 2016.5.28.0
Copyright &#169; 2006-2016, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
-------------------------------
Clearing any prior web/markdown output...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: C:\Users\Robert\Documents\GitHub\EX3\EX3\EX3\bin\Debug\EX3.XML
Source: C:\Users\Robert\Documents\GitHub\EX3\EX3\EX3\bin\Debug\EX3.dll
    Found assembly &#39;C:\Users\Robert\Documents\GitHub\EX3\EX3\EX3\bin\Debug\EX3.dll&#39;

Copying XML comments files
    C:\Users\Robert\Documents\GitHub\EX3\EX3\EX3\bin\Debug\EX3.XML -&gt; C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation\Help\Working\EX3.XML
</buildStep>
<buildStep step="GenerateSharedContent">
Generating shared content files (en-US, English (United States))...
<plugIn name="Lightweight Website Style" behavior="After" priority="1000">
</plugIn>    Last step completed in 00:00:00.0100
</buildStep>
<buildStep step="GenerateApiFilter">
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00.0000
</buildStep>
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
<plugIn name="Assembly Binding Redirection" behavior="Before" priority="1000">
Adding ignored assembly names to assembly resolver configuration:
    BusinessObjects.Licensing.KeycodeDecoder
    Microsoft.VisualStudio.TestTools.UITest.Playback
    Mono.Android
    OpenTK
</plugIn>[C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe - GenerateRefInfo.proj]
Build started 7/16/2016 11:06:40 PM.
The target &quot;_ConvertPdbFiles&quot; listed in a BeforeTargets attribute at &quot;C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)&quot; does not exist in the project, and will be ignored.
The target &quot;_CollectPdbFiles&quot; listed in an AfterTargets attribute at &quot;C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)&quot; does not exist in the project, and will be ignored.
The target &quot;_CollectMdbFiles&quot; listed in a BeforeTargets attribute at &quot;C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,38)&quot; does not exist in the project, and will be ignored.
The target &quot;_CopyMdbFiles&quot; listed in an AfterTargets attribute at &quot;C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (41,71)&quot; does not exist in the project, and will be ignored.
Project &quot;C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation\Help\Working\GenerateRefInfo.proj&quot; on node 1 (default targets).
PrepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
GenerateRefInfo:
  MRefBuilder (v2016.5.28.0)
  Copyright c 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : warning : Ignoring unresolved assembly reference: Mono.Android (Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065) required by EX3 [C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : warning : Ignoring unresolved assembly reference: OpenTK (OpenTK, Version=0.9.9.3, Culture=neutral, PublicKeyToken=84e04ff9cfb79065) required by EX3 [C:\Users\Robert\Documents\GitHub\EX3\EX3\Documentation\Help\Working\GenerateRefInfo.proj]

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Compiler.Metadata.MemoryCursor.ReadUTF8(Int32 bytesToRead)
   at System.Compiler.Metadata.Reader.GetCustomAttributeLiteralValue(MemoryCursor sigReader, TypeNode&amp; type)
   at System.Compiler.Metadata.Reader.GetCustomAttributeNamedArguments(ExpressionList arguments, UInt16 numNamed, MemoryCursor sigReader)
   at System.Compiler.Metadata.Reader.GetCustomAttribute(Method cons, MemoryCursor sigReader, Int32 blobLength)
   at System.Compiler.Metadata.Reader.GetCustomAttribute(Int32 i)
   at System.Compiler.Metadata.Reader.GetCustomAttributesFor(Int32 parentIndex)
   at System.Compiler.Metadata.Reader.GetTypeAttributes(TypeNode type, Object handle)
   at System.Compiler.TypeNode.get_Attributes()
   at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsExposedType(TypeNode type)
   at Microsoft.Ddue.Tools.Reflection.ApiFilter.NamespaceContainsExposedTypes(Namespace space)
   at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsExposedNamespace(Namespace space)
   at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis()
   at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args)
   at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;InitializeAndExecuteTask&gt;d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(TaskLoggingContext taskLoggingContext, ItemBucket bucket, IDictionary`2 taskIdentityParameters, TaskHost taskHost, TaskExecutionMode howToExecuteTask)
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteBucket&gt;d__19.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Dictionary`2 lookupHash)
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteTask&gt;d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TaskExecutionMode mode, Lookup lookup)
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteTask&gt;d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TargetLoggingContext loggingContext, BuildRequestEntry requestEntry, ITargetBuilderCallback targetBuilderCallback, ProjectTargetInstanceChild taskInstance, TaskExecutionMode mode, Lookup inferLookup, Lookup executeLookup, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.TargetEntry.&lt;ProcessBucket&gt;d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(ITaskBuilder taskBuilder, TargetLoggingContext targetLoggingContext, TaskExecutionMode mode, Lookup lookupForInference, Lookup lookupForExecution)
   at Microsoft.Build.BackEnd.TargetEntry.&lt;ExecuteTarget&gt;d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry requestEntry, ProjectLoggingContext projectLoggingContext, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.TargetBuilder.&lt;ProcessTargetStack&gt;d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(ITaskBuilder taskBuilder)
   at Microsoft.Build.BackEnd.TargetBuilder.&lt;BuildTargets&gt;d__11.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.RequestBuilder.&lt;BuildProject&gt;d__57.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.&lt;BuildAndReport&gt;d__49.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
   at Microsoft.Build.BackEnd.RequestBuilder.&lt;RequestThreadProc&gt;d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters)
   at Microsoft.Build.BackEnd.RequestBuilder.&lt;StartBuilderThread&gt;b__44_2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
    Last step completed in 00:00:15.7180
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
`

**Comment by EWSoftware** [comment]
What framework was the executable built against? .NET Portable Framework, NET Core, Windows Phone, Universal, etc.?  If so, selecting the appropriate framework version in the Build category of properties may resolve it.

The executable being parsed by MRefBuilder.exe is causing it to fail for some reason.  If using the appropriate framework doesn't resolve the issue, can you attach the failing project here or e-mail it to me so that I can diagnose the issue?

**Comment by PluginIO** [comment]
### Thanks for the apology

Oh wait, there wasn't one.

### How hard is this?

Parse XML > Composite State Machine > Root.Print() > WriteLine("<htm...

### Uninstalling/repairing

I'm now sat watching a 4GB repair download unknowing if it's going to fix my system. My time is $600 per day. You can probably understand from my tone that I'm a little tired of helping out people who cost me $600, repairing a system. *And in a simple XML parser*, but I digress.

### You have my bug report

`@see Just up there ^` I already provided you with a quite thorough bug report, so I invite you to use *your* time to go figure it out or to pull your software as *it has critically damaging errors*. I'm currently removing this software it from my machine.

**Comment by EWSoftware** [comment]
Please yourself.  Since you're the only one experiencing the problem, if you aren't going to answer my questions or provide me with something I can use to reproduce the problem, I can't help you.  Being rude will get you nowhere.
