### ISSUE TITLE
After upgrade from Version 1980 to 2016.5.23.0, projects no longer build

### ISSUE THREAD

**Issue by AnnieEmm** [EWSoftware/SHFB#324]
I'm on a Windows 7 machine, and have been using Sandcastle for several years. I installed a new version (2016.5.23.0), and my projects no longer build. I get this error message after getting to the custom build component configurations:

======================
Merging custom build component configurations
C:\sandcastle_help\webgrabber\Help\Working\sandcastle.config
  Updating reference topic configurations.
    Last step completed in 00:00:00.0312
-------------------------------

SHFB: Error BE0018: Unable to transform template text '<component id="IntelliSense Component" type="Microsoft.Ddue.Tools.IntelliSenseComponent" assembly="{@SandcastlePath}ProductionTools\BuildComponents.dll"><output includeNamespaces="true" namespacesFile="Namespaces" folder="{@OutputFolder}" /></component>': Exception has been thrown by the target of an invocation.
   at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.TransformText(String templateText, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.MergeConfigurations(XmlDocument config, Boolean isConceptualConfig)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.MergeComponentConfigurations()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.OnFieldMatch(Match match)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.TransformText(String templateText, Object[] args)

One or more component or plug-in configurations in this project contains an obsolete path setting.  Please remove the custom components and plug-ins and add them again so that their configurations are updated.  See the version release notes for information on breaking changes that require this update.
   at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.SandcastlePath()

**Comment by EWSoftware** [comment]
Do what it says in the message above:

> Remove all custom build components and plug-ins from your project, re-add them, and configure them so that they get the updated configuration elements.

A significant number of changes have occurred since v1.9.8.0.  Read through the release notes to see what has been changed.  Several deprecated options have been removed.

**Comment by AnnieEmm** [comment]
Hmm, I'm pretty clueless. I do not recall adding any custom components or plug-ins, whatever they may be. I guess I'll try uninstalling and reinstalling 1980, I've got some pretty tight deadlines I'm up against.

**Comment by EWSoftware** [comment]
If you have them, and you do based on the message, you'll find them in the project properties on the Components and Plug-Ins property pages.
