### ISSUE TITLE
Exception: Reference to undeclared entity while parsing Html entity

### ISSUE THREAD

**Issue by Atrejoe** [EWSoftware/SHFB#484]
The Xml documentation for one of my (imported) components provides a sample in which the currency symbol (pound) is Html encoded (not Xml encoded):

```
...
a currency symbol. For example, <code>$99.99</code> and <code>200&pound;</code>
...
```

Which causes:

```
...
-------------------------------
Generating namespace summary information...
    Last step completed in 00:00:00.3389
-------------------------------

SHFB: Error BE0065: BUILD FAILED: Reference to undeclared entity 'pound'. Line 40788, position 80.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.ResolveEntity()
   at System.Xml.XmlLoader.LoadEntityReferenceNode(Boolean direct)
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Comments()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Members()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFileCollection.get_ContainsInheritedDocumentation()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

Is there any way I can ignore this error (or component?) Sandcastle seemed to have been more strict since I upgraded to v2017.05.15.0 (from a few versions earlier, so I don't exactly know when this was introduced.)

Of course I was also address it at the developers of the component itself.

**Comment by EWSoftware** [comment]
Limited support for entities has always been the case since it uses the underlying .NET classes to load the XML and they only recognize a handful of common entities.  The only known fix is to correct the file in question by using the numeric form or by adding the extra entity definitions to the XML file.

**Comment by Atrejoe** [comment]
I was in luck: the library being documented had been updated and they addressed the issue already. Issue resolved by updating the component.

I am pretty sure though that I have built this project in its current state with an older version of Sandcastle before.
