### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by tomwayco** [EWSoftware/SHFB#502]
Following this tutorial, I run into a build error on Step 5 where the the build cannot load the System.Runtime assembly:
http://ewsoftware.github.io/SHFB/html/d5dbf017-25f1-48cb-86db-90f76ee8f4d7.htm

Here is the build output:

-------------------------------
[Sandcastle Help File Builder and Tools, version 2017.5.15.0]
Creating output and working folders...
Finding tools...
The Sandcastle tools are located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\'
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in 'C:\Program Files (x86)\HTML Help Workshop\'
Locating components in the following folder(s):
    C:\aM_root
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Using framework reflection data for '.NET Framework 4.5' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework'
    Last step completed in 00:00:03.7038
-------------------------------

SHFB: Error BE0065: BUILD FAILED: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(AggregateCatalog catalog, String folder, HashSet`1 searchedFolders, Boolean includeSubfolders, CancellationToken cancellationToken)
   at Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(AggregateCatalog catalog, String folder, HashSet`1 searchedFolders, Boolean includeSubfolders, CancellationToken cancellationToken)
   at Sandcastle.Core.ComponentUtilities.CreateComponentContainer(IEnumerable`1 folders, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)

Cannot load a reference assembly for execution.

And the screenshot to go along with:

![image](https://user-images.githubusercontent.com/21149146/29317997-532ca88a-819c-11e7-862c-bbdfcac5a233.png)

**Comment by EWSoftware** [comment]
Try moving your SHFB project to a subfolder under it's current location (i.e. *C:\aM_root\SHFBTest*).  The project folder is scanned for build components and it's probably picking up an assembly from somewhere else in or under the current folder that is causing the problem.  Moving the SHFB project to its own subfolder should resolve the issue.

**Comment by chm-tm** [comment]
This can also happen due to a problem in the _component path_.
For example, I had a project having its `ComponentPath` project property set to the whole NuGet cache folder. At some day, the build started to fail since some reference assembly found its way into the NuGet cache folder, causing a `BadImageFormatException` in the same path as shown in this issue.
I needed to narrow down the `ComponentPath`, which by the way resulted in a performance boost.

**Comment by EWSoftware** [comment]
The latest release support NuGet packages natively so if they've been updated to work with the latest release and are available as NuGet packages, components, plug-ins, presentations styles, and syntax generators can be added to the SHFB project that way and the Component Path is no longer needed.
