### ISSUE TITLE
Improve output with inheritdoc issues

### ISSUE THREAD

**Issue by chm-tm** [EWSoftware/SHFB#557]
I encountered the following failure:
```
SHFB: Error GID0001: Unexpected error while generating inherited documentation:
System.Xml.XPath.XPathException: Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.
   at MS.Internal.Xml.XPath.CompiledXpathExpr.get_QueryTree()
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr, XPathNodeIterator context)
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr)
   at System.Xml.XPath.XPathNavigator.Select(XPathExpression expr)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.InheritNestedDocumentation(XmlNode member)
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.InheritDocumentation(XmlNode member)
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.ScanCommentsFiles()
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.Main(String[] args)
```
By accident, I used a function in the select attribute unknown to XPath, so this is my fault.
Since I only create the documentation due to new releases, it's always quite a laborious task to locate the defective code in my sources, when this happens.

I believe that if the error text contained more information about the source, this could be straight forward. Giving source line information would be perfect, but might be hard to implement. Seeing the member name and the string passed to XPath could help a lot already.

**Comment by mikasoukhov** [comment]
Will put my details. Now SHFB still do not process inheritdoc well. In output I get the following

BuildAssembler : warning : ShowMissingComponent: [M:StockSharp.Alerts.AlertRuleField.GetHashCode] Missing <summary> documentation

for the following xml

    <member name="M:StockSharp.Alerts.AlertRuleField.GetHashCode">
      <inheritdoc />
    </member>

**Comment by EWSoftware** [comment]
@mikasoukhov: That's output from BuildAssembler, not the inherited docs tool.  You need to look further back in the log to the Generate Inherited Documentation build step for any issues related to that member ID.

If you want to pursue this further, please create a separate work item as this isn't relevant to this work item.

**Comment by EWSoftware** [comment]
It can't give source code line info since it's only dealing with the generated XML comments file at that point.  I can include the member ID and the expression used when the error occurred though.
