### ISSUE TITLE
Presentation Style VS2013 Gives NullRef error

### ISSUE THREAD

**Issue by Gerolkae** [EWSoftware/SHFB#571]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected error while executing plug-in 'Lightweight Website Style': System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.	Furcadia Framework Help	SHFB	0	

I am using the Current Version of SandCastle
msbuild tools 2015 installed
I'm using VS 2017

Log from Sandastle

SHFB: Error BE0029: Unexpected error while executing plug-in 'Lightweight Website Style': System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.GenerateTocAncestor(XElement ancestor, Int32 level, Boolean expanded)
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.<>c__DisplayClass7_0.<Execute>b__0(XElement element)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.GenerateTocAncestor(XElement ancestor, Int32 level, Boolean expanded)
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.<>c__DisplayClass7_0.<Execute>b__0(XElement element)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.GenerateWebsite()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)

Object reference not set to an instance of an object.
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.GenerateTocAncestor(XElement ancestor, Int32 level, Boolean expanded)
   at SandcastleBuilder.PlugIns.LightweightWebsiteStylePlugIn.<>c__DisplayClass7_0.<Execute>b__0(XElement element)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by EWSoftware** [comment]
This appears to be a duplicate of #556 and #559 and a minor point release was issued to correct it.  Please make sure you are using the latest release (v2017.12.30.2 not v2017.12.30.0).

If you are using the ".2" version, please attach an example that can be used to duplicate the issue.

**Comment by Gerolkae** [comment]
OH
I didn't recognize 556,
