### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: &#39;&#39;, hexadecimal value 0x08, is an invalid character. Line 3422, position 282.

### ISSUE THREAD

**Issue by bjakobitz** [EWSoftware/SHFB#574]
I am trying to build a help file.  I started by putting just my dlls in sources.  I was then prompted to add the references from my project.  Now I am getting this stack trace:
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/1700070/LastBuild.log)

<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: &#39;&#39;, hexadecimal value 0x08, is an invalid character. Line 3422, position 282.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32&amp; charCount, EntityType&amp; entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32&amp; charCount, EntityType&amp; entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32&amp; startPos, Int32&amp; endPos, Int32&amp; outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at Sandcastle.Core.ComponentUtilities.&lt;XmlStreamAxis&gt;d__22.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFileCollection.&lt;GetReferencedNamespaces&gt;d__6.MoveNext()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>

I am wondering if you can tell me which file is causing this error.  If it is in a supporting dll to which I don't have the source code is there a way I can tell SHFB to ignore that dll?

**Comment by EWSoftware** [comment]
The error is coming from an XML comments file with an invalid character (hex 08 in this case on line 3422 column 282 or near about).  It'll be either an XML comments file for your documentation sources or perhaps one of the reference assemblies.

If it's a reference assembly, you can make a copy of the XML comments file, fix the issue, and add the XML comments file as a documentation source which should override the one being pulled in automatically for the reference.  Since it's just an XML comments file, nothing from the assembly will show up as part of what gets documented for your assemblies.

There have been some issues recently with invalid XML comments files in NuGet packages so I'm going to add a fix for those by ignoring invalid XML comments files in a future release.  That fix would also take care of this issue.

**Comment by bjakobitz** [comment]
First off, thank you for the quick response.  Just out of curiosity, do you have a timeline set for your next release?  Is there a way I can force SHFB to ignore a dependency if I know it is giving me trouble and I don't need the documentation for the library?

**Comment by EWSoftware** [comment]
You can use the [assembly binding redirection plug-in](http://ewsoftware.github.io/SHFB/html/f5051d32-b973-4fe1-9ffe-e30531007691.htm).  On the Ignore If Unresolved tab, just add the assembly name to ignore if it can't be resolved.

I don't have a timeline for the next release.

**Comment by bjakobitz** [comment]
The plug-in worked.  Thank you for helping me out.

**Comment by Guson** [comment]
I am building a help file with several projects, and with one offending project. I created a new SHBF-project to try to isolate the offending file, but I can’t figure the problem. The problem seems like this reported “SHFB: Error BE0065”. I will try use the [assembly binding redirection plug-in](http://ewsoftware.github.io/SHFB/html/f5051d32-b973-4fe1-9ffe-e30531007691.htm).

Q: Where can I find the _offending_ assembly or filename?

## Build Output
`[Sandcastle Help File Builder and Tools, version 2017.12.30.2]`
...
`SHFB: Error BE0065: BUILD FAILED: The 'br' start tag on line 507 position 385 does not match the end tag of 'p'. Line 507, position 391.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Comments()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFile.get_Members()
   at SandcastleBuilder.Utils.BuildEngine.XmlCommentsFileCollection.get_ContainsInheritedDocumentation()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()`

Build log file
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/1788657/LastBuild.log)

**Comment by Guson** [comment]
Added all external references below `References to include`, to _Assembly Name to Ignore_, but no success.
