### ISSUE TITLE
Cannot build - new installation windows 10

### ISSUE THREAD

**Issue by itaibech** [EWSoftware/SHFB#575]
Hi , 
i got this error when i try to build it.
i have no clue why it's trying to access My Music folder.

SHFB: Error BE0065: BUILD FAILED: Access to the path 'C:\Users\ibechor\Documents\My Music' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at Sandcastle.Core.Reflection.ReflectionDataSetDictionary..ctor(IEnumerable`1 componentLocations)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
You've probably got the SHFB project directly in the My Documents folder.  SHFB will scan the project folder and subfolders for components.  Move your project to a subfolder under My Documents rather than directly in it.  That way, it won't search all the other folders.
