### ISSUE TITLE
Build Failed - GenerateInheritedDocs.proj

### ISSUE THREAD

**Issue by Asadlerpwcom** [EWSoftware/SHFB#595]
Hi,

When i try to build the project the following build error happens:

Generating inherited documentation...
[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe - GenerateInheritedDocs.proj]
Sandcastle Help File Builder and Tools, version 2017.12.30.2
Copyright ¸ 2006-2017, Eric Woodruff, All Rights Reserved
E-Mail: Eric@EWoodruff.us

Reflection information will be retrieved from 'reflection.xml'
Inherited documentation will be written to '_InheritedDocs_.xml'
Indexing C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\*.xml
Indexing C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\*.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\UmbracoExamine.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\Umbraco.Web.UI.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\umbraco.providers.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\umbraco.MacroEngines.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\umbraco.editorControls.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\umbraco.DataLayer.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\Umbraco.Core.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\umbraco.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.WebPages.Razor.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.WebPages.Deployment.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.WebPages.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.Razor.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.Mvc.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.Http.WebHost.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.Http.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.Web.Helpers.xml
Indexing D:\Dev\Sandcastle Test\Help\Working\System.ValueTuple.xml
SHFB: Error GID0001: Unexpected error while generating inherited documentation:
System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: The 'p' start tag on line 1241 position 2 does not match the end tag of 'th'. Line 1241, position 92.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at SandcastleBuilder.Utils.InheritedDocumentation.IndexedCommentsCache.<>c__DisplayClass25_0.<IndexCommentsFiles>b__0(String filename)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SandcastleBuilder.Utils.InheritedDocumentation.IndexedCommentsCache.IndexCommentsFiles(String path, String wildcard, Boolean recurse, ConcurrentBag`1 commentsFiles)
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.LoadConfiguration(String configFile)
   at SandcastleBuilder.InheritedDocumentation.GenerateInheritedDocs.Main(String[] args)
---> (Inner Exception #0) System.Xml.XmlException: The 'p' start tag on line 1241 position 2 does not match the end tag of 'th'. Line 1241, position 92.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at SandcastleBuilder.Utils.InheritedDocumentation.IndexedCommentsCache.<>c__DisplayClass25_0.<IndexCommentsFiles>b__0(String filename)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

    Last step completed in 00:00:00.9575
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Any help would be appreciated

**Comment by EWSoftware** [comment]
It's caused by an invalid XML comments file which is, unfortunately, a common occurrence with many of the NuGet packages being created by Microsoft these days.  I've got a workaround in place for the next release which will ignore the invalid files.

For the time being, the only workaround is to track down and fix the invalid XML comments file.  Since System.ValueTuple.xml is listed last as the one being indexed, that's probably the place to start.  You'll probably find all the package XML comments files in the working folder with it so you should be able to find the bad one.  You'll need to fix it at the source which is usually in one of the package cache folders.

See the related issues #560, #569, and #574 for more information.

**Comment by Asadlerpwcom** [comment]
You were spot on with that package, i have updated it to a pre-release 4.5.0 which seems to have fixed the issue.

I tried to add it to the ignore plugin however this didn't seem to work.
