### ISSUE TITLE
Could not load file or assembly Microsoft.Build

### ISSUE THREAD

**Issue by RickZeeland** [EWSoftware/SHFB#638]
I'm getting the following error after installing the latest version of SHFB on Windows 10 with VS2017:

> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at SandcastleBuilder.Gui.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Any ideas of what could be wrong ?

**Comment by RickZeeland** [comment]
Installing the Microsoft Build Tools 2015 fixed the issue: 
[https://www.microsoft.com/en-us/download/details.aspx?id=48159](url)

**Comment by Kareem24** [comment]
I'm getting the same Message Error but still not finding any slotion

**Comment by EWSoftware** [comment]
Have you installed the MSBuild Tools 2015?  The link above doesn't work but the URL is correct.

**Comment by RickZeeland** [comment]
@EWSoftware I was wondering if by chance you are related to Bill Woodruff who is a CodeProject MVP ?
btw. thanks for your great SHFB :)

**Comment by EWSoftware** [comment]
No, no relation.

**Comment by Kareem24** [comment]
i did it !
Thank you fou this usefull info :)

**Comment by mtosoftware** [comment]
Many thanks.
