### ISSUE TITLE
Incompatible Visual Studio project file format

### ISSUE THREAD

**Issue by SoftCircuits** [EWSoftware/SHFB#713]
I just installed Sandcastle and tried to build a help project I created years ago but got an error. The help for the error didn't contain any useful information. My projects are .NET Core projects built with Visual Studio Community 2019.

> Validating and copying documentation source information
Source: D:\Users\Jonathan\source\repos\Toxic\Toxic.Desktop\Toxic.Desktop.csproj
    Found project 'D:\Users\Jonathan\source\repos\Toxic\Toxic.Desktop\Toxic.Desktop.csproj'
    Last step completed in 00:00:00.0410

> SHFB: Error BE0065: BUILD FAILED: Incompatible Visual Studio project file format.  See the error code help topic for more information.
This project may be for a newer version of MSBuild and cannot be loaded.  Error message:
   at SandcastleBuilder.Utils.MSBuild.MSBuildProject..ctor(String projectFile)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

> The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\Users\Jonathan\source\repos\Toxic\Toxic.Desktop\Toxic.Desktop.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectParser.Parse(XmlDocumentWithLocation document, ProjectRootElement projectRootElement)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.<>c__DisplayClass170_0.<OpenProjectOrSolution>b__0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at SandcastleBuilder.Utils.MSBuild.MSBuildProject..ctor(String projectFile)

**Comment by EWSoftware** [comment]
Are you using Visual Studio or the standalone GUI to build the SHFB project?  The standalone GUI doesn't support the newer MSBuild project formats used by .NET Core/Standard.  The Visual Studio extension does support them.

**Comment by SoftCircuits** [comment]
Yes, I'm using the standalone app.

**Comment by SoftCircuits** [comment]
So, I restarted the installer and went to the *SHFB Visual Studio Package* section and clicked *Install Package*.

> Unexpected exit code returned from VSIX installer trying to install the package: -532462766

**Comment by EWSoftware** [comment]
Just run the VSIX installer manually from the .\InstallResources folder.
