### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED

### ISSUE THREAD

**Issue by nsantec** [EWSoftware/SHFB#716]
```
<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2019.4.14.0" projectFile="C:\src\Commerce.SDK\Documentation\Sitecore.Commerce.Documentation.shfbproj" started="2019-06-17 3:29:00 PM">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\src\Commerce.SDK\Documentation\packages\EWSoftware.SHFB.2019.4.14\tools\&#39;
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    C:\src\Commerce.SDK\Documentation\packages\EWSoftware.SHFB.NETFramework.4.7\tools\Data\
    C:\src\Commerce.SDK\Documentation
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\src\Commerce.SDK\Documentation\packages\EWSoftware.SHFB.2019.4.14\tools\
Using framework reflection data for &#39;.NET Framework 4.6.2&#39; located in &#39;C:\src\Commerce.SDK\Documentation\packages\EWSoftware.SHFB.NETFramework.4.7.2\tools\Data\.NETFramework&#39;
    Last step completed in 00:00:09.5196
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: Type handle &#39;⁪‍‍‫‎‎⁬​‎‫‪⁮‫⁮‬‎‫⁪‏⁪‏‏‎​‭⁯‍‎‌‭⁭‮‫‭‮‌⁮⁭‮‎‮&#39; and method handle with declaring type &#39;‮⁬‬‪‮⁬‏‪​‭‮‭‏‪‎‪‌‎⁪‭‪‮‎⁬​⁮⁮⁬‪⁯‌⁯‌⁫‮‬‏‪‌‏‮&#39; are incompatible. Get RuntimeMethodHandle and declaring RuntimeTypeHandle off the same MethodBase.
   at System.RuntimeType.GetMethodBase(RuntimeType reflectedType, RuntimeMethodHandleInternal methodHandle)
   at System.Reflection.Associates.AssignAssociates(Int32 tkMethod, RuntimeType declaredType, RuntimeType reflectedType)
   at System.Reflection.Associates.AssignAssociates(MetadataImport scope, Int32 mdPropEvent, RuntimeType declaringType, RuntimeType reflectedType, RuntimeMethodInfo&amp; addOn, RuntimeMethodInfo&amp; removeOn, RuntimeMethodInfo&amp; fireOn, RuntimeMethodInfo&amp; getter, RuntimeMethodInfo&amp; setter, MethodInfo[]&amp; other, Boolean&amp; composedOfAllPrivateMethods, BindingFlags&amp; bindingFlags)
   at System.Reflection.RuntimePropertyInfo..ctor(Int32 tkProperty, RuntimeType declaredType, RuntimeTypeCache reflectedTypeCache, Boolean&amp; isPrivate)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateProperties(Filter filter, RuntimeType declaringType, Dictionary`2 csPropertyInfos, Boolean[] usedSlots, ListBuilder`1&amp; list)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateProperties(Filter filter)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetListByName(Char* pName, Int32 cNameLen, Byte* pUtf8Name, Int32 cUtf8Name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.Populate(String name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetMemberList(MemberListType listType, String name, CacheType cacheType)
   at System.RuntimeType.GetPropertyCandidates(String name, BindingFlags bindingAttr, Type[] types, Boolean allowPrefixLookup)
   at System.RuntimeType.GetProperties(BindingFlags bindingAttr)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.&lt;GetExportMembers&gt;d__34.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable()
   at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable(Type type, ICompositionElement origin)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetEnumerator()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(AggregateCatalog catalog, String folder, HashSet`1 searchedFolders, Boolean includeSubfolders, CancellationToken cancellationToken)
   at Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(AggregateCatalog catalog, String folder, HashSet`1 searchedFolders, Boolean includeSubfolders, CancellationToken cancellationToken)
   at Sandcastle.Core.ComponentUtilities.CreateComponentContainer(IEnumerable`1 folders, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>

```

**Comment by EWSoftware** [comment]
It looks like whatever you posted got completely mangled.  Can you edit and repost that in plain text?

**Comment by EWSoftware** [comment]
No response so closing for now.  If more info can be provided, it can be reopened.
