### ISSUE TITLE
Cannot install Visual Studio Package for v2019.6.24.0

### ISSUE THREAD

**Issue by alekdavis** [EWSoftware/SHFB#730]
Tried a couple of times (one ran the installer as Administrator). At the Sandcastle Help File Builder Visual Studio Package installation step, I'm getting error:

> VSHiveStub.exe failed: PkgdefManagement failedto create application: "0x80070057".

The log file shows these:

```
7/30/2019 8:50:01 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\8.1\Windows Store SDK\extension.vsixmanifest'
7/30/2019 8:50:01 AM - Skipping 'C:\Users\MYUSERID\AppData\Local\Microsoft SDKs' as it doesn't exist
7/30/2019 8:50:01 AM - END: Processing extension pack
7/30/2019 8:50:01 AM - END: Processing extension pack
7/30/2019 8:50:01 AM - System.InvalidOperationException: VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070057".
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData, List`1 supportedSKUs, String uninstallableVsixId, String extensionPackParentName, List`1 uninstallVsixIds)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToUnInstall(IStateData stateData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
The installer correctly identifies the Visual Studio 2017 instance (the only version of VS I have installed). I do not have VS running when running the SHFB installer.

**Comment by EWSoftware** [comment]
There's probably an issue with the Visual Studio installation.  I'd try repairing it or updating it with the latest patches.

**Comment by alekdavis** [comment]
Thank you. Something was indeed wrong with VS update module. I reran the VS update and it fixed the issue.
