### ISSUE TITLE
SandcastleInstaller.exe fails when installing SHFBVisualStudioPackage_VS2015AndLater.exe

### ISSUE THREAD

**Issue by muthink** [EWSoftware/SHFB#741]
Machine Configuration: Microsoft Windows [Version 10.0.17763.720], Visual Studio 2017 [Version 15.9.15] w/ Build Tools installed
Stesp:
1. Reboot machine
2. Check all install files are local and unblocked.
3. Start and then close Visual Studio 2017,to make sure no pending operations
4. Start SandcastleInstaller.exe in Administrator mode.
5. Click next on wizard until arriving at "Sandcastle Help File Builder Visual Studio Package" screen
6. Verify that installer has detected Visual Studio and Build Tools
•	Visual Studio Build Tools 2017
•	Visual Studio Enterprise 2017
7. Click "Install Package"
8. Installer fails:
![image](https://user-images.githubusercontent.com/1256768/64027420-ac2b2480-cb0e-11e9-9d3d-4a10dd7739b8.png)
9. Log attached below:
8/30/2019 10:12:02 AM - Microsoft VSIX Installer
8/30/2019 10:12:02 AM - -------------------------------------------
8/30/2019 10:12:02 AM - vsixinstaller.exe version:
8/30/2019 10:12:02 AM - 16.3.1061
8/30/2019 10:12:02 AM - -------------------------------------------
8/30/2019 10:12:02 AM - Command line parameters:
8/30/2019 10:12:02 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\source\Temp\Sandcastle\InstallResources\SHFBVisualStudioPackage_VS2015AndLater.vsix
8/30/2019 10:12:02 AM - -------------------------------------------
8/30/2019 10:12:02 AM - Microsoft VSIX Installer
8/30/2019 10:12:02 AM - -------------------------------------------
8/30/2019 10:12:03 AM - System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.VisualStudio.Setup.Configuration.ISetupInstance2.GetState()
   at VSIXInstaller.SetupExtensions.GetLaunchableInstances(ISetupConfiguration2 configuration)
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
   at VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
   at VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
   at VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by EWSoftware** [comment]
I don't know why "Visual Studio Build Tools 2017" listed separately as it's not typically something you can install SHFB in as far as I know.  I'd suggest unselecting it and try installing it in just the Enterprise version.  You can also try running the VSIX installer outside of the guided installer.  Since it's a COM component failure, you might also try repairing the Visual Studio installation as something might be broken with it.
