### ISSUE TITLE
Visual Studio 2019 community Solution Core.Net 3.0 (latest version install)

### ISSUE THREAD

**Issue by lnicolae** [EWSoftware/SHFB#777]
SHFB: Error BE0065: BUILD FAILED: Incompatible Visual Studio project file format.  See the error code help topic for more information.
This project may be for a newer version of MSBuild and cannot be loaded.  Error message:
   at SandcastleBuilder.Utils.MSBuild.MSBuildProject..ctor(String projectFile)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  F:\Work\TehnologCN3\Tehnolog\Tehnolog.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectParser.Parse(XmlDocumentWithLocation document, ProjectRootElement projectRootElement)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.<>c__DisplayClass170_0.<OpenProjectOrSolution>b__0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at SandcastleBuilder.Utils.MSBuild.MSBuildProject..ctor(String projectFile)

**Comment by EWSoftware** [comment]
Are you building this with the standalone GUI, from within Visual Studio, or using MSBuild?  The standalone GUI doesn't currently support the newer project format for documentation sources.  When used from Visual Studio or MSBuild it does.  .NET Core 3 is a later version but I don't think that should make a difference as far as the project format.

**Comment by lnicolae** [comment]
I use standalone version. Thank,

**Comment by EWSoftware** [comment]
The standalone version in the next release will support them.
