### ISSUE TITLE
Problems installing extension for Visual Studio Build Tools

### ISSUE THREAD

**Issue by mckool23** [EWSoftware/SHFB#916]
**Note:** This problem is more a configuration issue with Visual Studio, but I didn't find any help on this regard on the web until yet. 

I have a build server with Visual Studio Build Tools 2017 and 2022 installed. When I try to install the extensions here I am getting the error 2003 with message "This extension is not installable on any currently installed products.". In the log file I can read the following:

>...
28.06.2022 09:02:58 - -------------------------------------------
28.06.2022 09:02:58 - Microsoft VSIX Installer
28.06.2022 09:02:58 - -------------------------------------------
28.06.2022 09:02:58 - Skipping product Microsoft.VisualStudio.Product.BuildTools (e3a1713b) since it does not support extensions
28.06.2022 09:02:58 - Skipping product Microsoft.VisualStudio.Product.BuildTools (ff02bd06) since it does not support extensions
28.06.2022 09:02:58 - Initializing Install...
28.06.2022 09:02:58 - Extension Details...
28.06.2022 09:02:58 - 	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
28.06.2022 09:02:58 - 	Name               : SHFB (VS2017 and VS2019)
28.06.2022 09:02:58 - 	Author             : EWSoftware
28.06.2022 09:02:58 - 	Version            : 2022.2.6.0
28.06.2022 09:02:58 - 	Description        : Visual Studio integration for the Sandcastle Help File Builder.
28.06.2022 09:02:58 - 	Locale             : en-US
28.06.2022 09:02:58 - 	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
28.06.2022 09:02:58 - 	InstalledByMSI     : False
28.06.2022 09:02:58 - 	SupportedFrameworkVersionRange : [4.5,)
28.06.2022 09:02:58 - 
28.06.2022 09:02:58 - 	SignatureState     : Unsigned
28.06.2022 09:02:58 - 	Supported Products : 
28.06.2022 09:02:58 - 		Microsoft.VisualStudio.Community
28.06.2022 09:02:58 - 			Version : [15.0,17.0)
28.06.2022 09:02:58 - 			ProductArchitecture : x86
28.06.2022 09:02:58 - 
28.06.2022 09:02:58 - 	References         : 
28.06.2022 09:02:58 - 	Prerequisites      : 
28.06.2022 09:02:58 - 		-------------------------------------------------------
28.06.2022 09:02:58 - 		Identifier   : Microsoft.Component.MSBuild
28.06.2022 09:02:58 - 		Name         : MSBuild
28.06.2022 09:02:58 - 		Version      : [15.0,)
28.06.2022 09:02:58 - 
28.06.2022 09:02:58 - 		-------------------------------------------------------
28.06.2022 09:02:58 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
28.06.2022 09:02:58 - 		Name         : .NET desktop development tools
28.06.2022 09:02:58 - 		Version      : [15.0,)
28.06.2022 09:02:58 - 
28.06.2022 09:02:58 - Signature Details...
28.06.2022 09:02:58 - 	Extension is not signed.
28.06.2022 09:02:58 - 
28.06.2022 09:02:58 - Searching for applicable products...
28.06.2022 09:02:58 - Found installed product - Global Location
28.06.2022 09:02:58 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
...

So the question is, is there a way to workaround this and to install the extension for Visual Studio Build Tools?

Thanks in advance for the help .

**Comment by mckool23** [comment]
Mabye I misunderstood something here. I thought that one needs to have the extension installed to built using the command line. Checking again the help I read that MSBuild deployed with Visual Studio should be enough. 

I am getting an error when calling MSBuild. 
>13:25:55    D:\Tests\Project27\Help_en.shfbproj(134,3): error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

It seems as a variale **$(SHFBROOT)** in the project file is not being updated:
-- Import the SHFB build targets during build --
Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="'$(MSBuildRestoreSessionId)' == ''"

But it has the right value when a look at the environment variables within the system properties:
 
![Variable](https://user-images.githubusercontent.com/102285602/176170393-ac3a2443-2da1-439d-866b-289442335770.PNG)

Any advice on how to fix this?

**Comment by mckool23** [comment]
Found the problem. I forgot to do a reload of my build service.
