### ISSUE TITLE
Error and NullReferenceException when creating new project in My Documents

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#922]
For testing, I created a new project (`test.shfbproj`) in My Documents using the standalone GUI (2022.2.6).

Clicking on the `Build` entry then resulted in:

1. An error dialog: "Unexpected error loading reflection data set info: Access to the path 'C:\Users\xxx\Documents\My Music' is denied."
2. A crash dialog; using Continue allowed the GUI to keep going.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.WPF.PropertyPages.BuildPropertiesPageContent.LoadReflectionDataSetInfo(SandcastleProject currentProject)
   at SandcastleBuilder.Package.PropertyPages.BuildPropertiesPageControl.BindControlValue(String propertyName)
   at SandcastleBuilder.Package.PropertyPages.BasePropertyPage.BindProperties(ControlCollection controls)
   at SandcastleBuilder.Package.PropertyPages.BasePropertyPage.SetProject(SandcastleProject currentProject)
   at SandcastleBuilder.Gui.ContentEditors.ProjectPropertiesWindow.tvPropertyPages_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SandcastleBuilderGUI
    Assembly Version: 2021.10.23.0
    Win32 Version: 22.2.6.0
    CodeBase: file:///C:/Program%20Files%20(x86)/EWSoftware/Sandcastle%20Help%20File%20Builder/Tools/SandcastleBuilderGUI.exe
...
```

**Comment by Zastai** [comment]
Trying to build that project after adding a documentation source fails further:

```
SHFB: Error BE0065: BUILD FAILED: Access to the path 'C:\Users\xxx\Documents\My Music' is denied.
```

**Comment by EWSoftware** [comment]
Just like you wouldn't put a C# project file directly in My Documents with all of your source code files, SHFB projects need to be placed in their own subfolder with their content files.  In addition, the project folder is scanned for components thus, if you put it in My Documents, it will try to search all the subfolders under My Documents, some of which it likely doesn't have access to.  Using a subfolder to contain the project resolves that issue.

**Comment by Zastai** [comment]
Perhaps. While I'd understand a warning about not being able to look everywhere, I'm not sure a build error for it makes sense. Would it also error out if there was a `.git` or `.svn` folder there it could not fully scan, for example?

And the `NullReferenceException` should certainly be avoided.
