### ISSUE TITLE
Error BE0065: BUILD FAILED: Input string was not in a correct format.

### ISSUE THREAD

**Issue by RickZeeland** [EWSoftware/SHFB#941]
After upgrading our solution to .NET 4.8 and the new SHFB, I get the following error both from VS2019 and the GUI:

SHFB: Error BE0065: BUILD FAILED: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(MessageLevel level, String message)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(MessageLevel level, String message)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by RickZeeland** [comment]
After removing MS Build tools 2017 and installing MS Build tools 2019 another error occurs:

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2827,5): warning MSB3290: Failed to create the wrapper assembly for type library "MSTSCLib". Access to the path 'obj\Debug\Interop.MSTSCLib.dll' is denied. [C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\GenerateRefInfo-4ff863e4-099e-4be3-9b4d-c8c0d78e282e.proj]
  C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\AxImp.exe C:\Windows\SysWOW64\mstscax.dll /out:obj\Debug\AxInterop.MSTSCLib.dll 
AXIMP : AxImp error : Error writing to output file 'C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\obj\Debug\MSTSCLib.dll'. [C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\GenerateRefInfo-4ff863e4-099e-4be3-9b4d-c8c0d78e282e.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2827,5): warning MSB3283: Cannot find wrapper assembly for type library "AxMSTSCLib". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit. [C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\GenerateRefInfo-4ff863e4-099e-4be3-9b4d-c8c0d78e282e.proj]
Done Building Project "C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\GenerateRefInfo-4ff863e4-099e-4be3-9b4d-c8c0d78e282e.proj" (default targets) -- FAILED.
    Last step completed in 00:00:05,0410
-------------------------------
Applying document model to reflection output...
    Last step completed in 00:00:00,0010
-------------------------------

SHFB: Error BE0065: BUILD FAILED: Could not find file 'C:\Projects\VMS\VMS\DesignNotes\API Docs\Genereren van de API documentatie\SandCastle\Help\Working\reflection.org'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Sandcastle.Core.PresentationStyle.StandardDocumentModel.ApplyDocumentModel(String reflectionDataFile, String docModelReflectionDataFile)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
If you have VS2019 installed, it would be using the 2019 build tools anyway.  The second error may be unrelated to the first as it appears to be a locked file issue.  That may be due to build order.  Can you provide an example that duplicates the issue?

**Comment by RickZeeland** [comment]
Thanks for your reply Eric, I'm afraid our solution has become a hodge-podge of about 200 .NET 4.8, .NET Core, .NET Standard and ASP.NET Core projects. So it's hard to provide an example, but I'll see if I can pinpoint the cause.
I was also wondering if SHFB works with .NET 6 ? we are planning to upgrade.

**Comment by RickZeeland** [comment]
Got things building again after creating a new project and selecting the dll's instead of the project files (all needed dll's are now in the same directory).
:)

**Comment by EWSoftware** [comment]
It should work with .NET 6.  You'd select the ".NET Core/.NET Standard/.NET 5.0+" option for the framework version in the SHFB project.

**Comment by MarcelVersteeg** [comment]
I am also having this issue.

I am building the documentation directly from a solution, using SandCastle version 2022.8.14.1. My project is based on .NET Framework 4.6.2.

Any other solution than recreating the project and directly referencing the dll's? Referencing the solution is just making it easy for maintenance.

**Comment by ketchup201** [comment]
I'm experiencing the same issue. It's due to the XML file in my project. If you comment out the XML file, then it successfully creates the help. Leaving in the XML file will cause this error to be generated. This is a showstopper for me, so any help or guidance you can provide would be extremely appreciated!
[scastle.zip](https://github.com/EWSoftware/SHFB/files/9711442/scastle.zip)

**Comment by MarcelVersteeg** [comment]
> I'm experiencing the same issue. I believe it's due to the XML file in my project. For example, if you comment out the XML file from the project file, then it successfully creates the help. Leaving in the XML file will cause this error to be generated. This is a showstopper for me, so any help or guidance you can provide would be extremely appreciated! ZIP file attached that replicates the error. Maybe the error occurs due to line 2988 of the XML file? It might be the same issue that Marcel encountered, due to his description. [scastle.zip](https://github.com/EWSoftware/SHFB/files/9711442/scastle.zip)

At least the stack dump of the error is identical, but with a quick glance I am not able to relate it to line 2988 of the XML file specifically. There are more locations where there is a text between `{` and `}`, not only in the method names, but also in the documentation itself. I have commented out all methods that have these `{` and `}` somewhere in the method name and the documentation in the XML file in the zip-file provided by @ketchup201, and then the build also succeeds. This seems to indeed lead to my previous analysis.

**Comment by ketchup201** [comment]
In my case, the offending bit has nested curly braces. Maybe that's the issue.
`<member name="M:HighView.Containering.Search.QueryAgents.IQueryAgentEmail.CustomAgentEmail(HighView.Containering.Search.QueryAgents.QueryAgent,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.UInt64}},System.String@,System.String@)">`

**Comment by MarcelVersteeg** [comment]
@EWSoftware Are you able to reproduce this issue using @ketchup201's example?

**Comment by ketchup201** [comment]
Not sure if this helps, but when I eliminated that one method from the help by using the API filter, the error no longer occurred.

**Comment by EWSoftware** [comment]
I was able to duplicate the issue and fix it.

**Comment by ketchup201** [comment]
THANK YOU!!!
