### ISSUE TITLE
Null Reference Exception when transforming reflection data to a topic

### ISSUE THREAD

**Issue by MCFHTAGENTS** [EWSoftware/SHFB#973]
Also seeing this error:
````
SHFB: Error BE0065: BUILD FAILED: TransformComponent: [Overload:Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.&lt;&gt;c.&lt;RenderApiTypeMemberLists&gt;b__67_1(XElement el)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.&lt;GetEnumerator&gt;d__1.MoveNext()
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiTypeMemberLists(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiMemberList(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(String componentName, MessageLevel level, String key, String message)
   at Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(String key, MessageLevel level, String message, Object[] args)
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at Sandcastle.Tools.BuildComponents.SwitchComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.Apply(IEnumerable`1 topics)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0()
   at System.Threading.Tasks.Task.Execute()

One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()







TransformComponent: [Overload:Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.&lt;&gt;c.&lt;RenderApiTypeMemberLists&gt;b__67_1(XElement el)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.&lt;GetEnumerator&gt;d__1.MoveNext()
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiTypeMemberLists(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiMemberList(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(String componentName, MessageLevel level, String key, String message)
   at Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(String key, MessageLevel level, String message, Object[] args)
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at Sandcastle.Tools.BuildComponents.SwitchComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.Apply(IEnumerable`1 topics)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0()
   at System.Threading.Tasks.Task.Execute()
````

**Comment by EWSoftware** [comment]
It looks like you're documenting the Microsoft.EntityFrameworkCore assemblies.  Was that intentional?  Do you have the entity framework assemblies included as documentation sources rather than reference assemblies?  If so, moving them over to be references instead would likely work around the issue for the time being.  I can use it as a documentation source to try and duplicate the issue.

**Comment by MCFHTAGENTS** [comment]
Eric,
Yes I have worked around it -  was creating a reference project to hide them all from my main help file and it compiles enough that the main helpfile then works.
Thank you
Mark
