### ISSUE TITLE
Duplicate Topic Types and File Names

### ISSUE THREAD

**Issue by colsonab** [EWSoftware/SHFB#984]
The following code

```
        public static IRuleBuilderOptions<T, decimal?> PositiveMoneyAmount<T>(this IRuleBuilder<T, decimal?> ruleBuilder)
        {
            return ...
        }

        public static IRuleBuilderOptions<T, decimal> PositiveMoneyAmount<T>(this IRuleBuilder<T, decimal> ruleBuilder)
        {
            return ...
        }

        public static IRuleBuilderOptions<T, decimal> MoneyAmount<T>(this IRuleBuilder<T, decimal> ruleBuilder)
        {
            return ...
        }

        public static IRuleBuilderOptions<T, decimal?> MoneyAmount<T>(this IRuleBuilder<T, decimal?> ruleBuilder)
        {
            return ...
        }
```

results in duplicate type and topic file names for both the overloaded extension method type names of _PositiveMoneyAmount_ and _MoneyAmount_ 

```
    <topic id="Overload:FluentValidatorExtensions.MoneyAmount" file="74DD15AD">
      <topic id="M:FluentValidatorExtensions.MoneyAmount``1(System.Boolean)" file="24A58B13" />
      <topic id="M:FluentValidatorExtensions.MoneyAmount``1(System.Boolean)" file="24A58B13" />
    </topic>
    <topic id="Overload:FluentValidatorExtensions.PositiveMoneyAmount" file="EBEB5AE1">
      <topic id="M:FluentValidatorExtensions.PositiveMoneyAmount``1(System.Boolean)" file="9DAA3827" />
      <topic id="M:FluentValidatorExtensions.PositiveMoneyAmount``1(System.Boolean)" file="9DAA3827" />
    </topic>
```

Of course, the signatures for the arguments are wrong (shouldn't be _System.Boolean_).  According to the XML comments file the types should be

```
M:FluentValidatorExtensions.PositiveMoneyAmount``1(FluentValidation.IRuleBuilder{``0,System.Nullable{System.Decimal}})
M:FluentValidatorExtensions.PositiveMoneyAmount``1(FluentValidation.IRuleBuilder{``0,System.Decimal})
M:FluentValidatorExtensions.MoneyAmount``1(FluentValidation.IRuleBuilder{``0,System.Decimal})
M:FluentValidatorExtensions.MoneyAmount``1(FluentValidation.IRuleBuilder{``0,System.Nullable{System.Decimal}})
```

The above happens both when XML Documentation is in the source code and when it is not.  

Here are other cases which demonstrate similar behavior with a _params_ modifier:

```
        public LoanQueryableRequest(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.Loan, object>>> includes,
            params Expression<Func<Data.Entities.Loan, bool>>[] conditions)
            : base(isTrackable, includes, conditions)
        {
        }

        public LoanQueryableRequest(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.Loan, object>>> includes,
            ICollection<Expression<Func<Data.Entities.Loan, bool>>> conditions)
            : base(isTrackable, includes, conditions)
        {
        }
    }
```

gets processed as

```
<topic id="Overload:LoanQueryableRequest.#ctor" file="40BA7A38">
  <topic id="M:LoanQueryableRequest.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="CE169886" />
  <topic id="M:LoanQueryableRequest.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="CE169886" />
</topic>
```

and

```
        public Request(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.LoanProcessing, object>>> includes,
            params Expression<Func<Data.Entities.LoanProcessing, bool>>[] conditions)
            : base(isTrackable, includes, conditions)
        {
        }

        public Request(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.LoanProcessing, object>>> includes,
            ICollection<Expression<Func<Data.Entities.LoanProcessing, bool>>> conditions)
            : base(isTrackable, includes, conditions)
        {
        }
```

gets processed as

```
<topic id="Overload:Queryable.Request.#ctor" file="2C3B683D">
  <topic id="M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="E60D4D8F" />
  <topic id="M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="E60D4D8F" />
</topic>
```

and

```
        public Request(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.OriginatedAchBatch, object>>> includes,
            params Expression<Func<Data.Entities.OriginatedAchBatch, bool>>[] conditions)
            : base(isTrackable, includes, conditions)
        {
        }

        public Request(
            bool isTrackable,
            ICollection<Expression<Func<Data.Entities.OriginatedAchBatch, object>>> includes,
            ICollection<Expression<Func<Data.Entities.OriginatedAchBatch, bool>>> conditions)
            : base(isTrackable, includes, conditions)
        {
        }
```

gets processed as

```
<topic id="Overload:Request.#ctor" file="A8812AB6">
  <topic id="M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="55FE74BB" />
  <topic id="M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="55FE74BB" />
</topic>
```

I am using SHFB v2023.3.4.0 with framework reflection data for _'Cross-platform (.NET Core/.NET Standard)'_ to create website documentation with the new **Default 2022** presentation style.  With this style the documentation builds but with duplicate key warnings like

```
Building help topics...
<plugIn name="Website Table of Contents Generator" behavior="Before" priority="1000">
Loading TOC info and adding unique IDs to parent nodes
SHFB: Warning WTOC0001: Duplicate key found in TOC.  This was unexpected.  Do you have the right framework version selected in the documentation project?  Duplicate key: M:LoanQueryableRequest.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)
SHFB: Warning WTOC0001: Duplicate key found in TOC.  This was unexpected.  Do you have the right framework version selected in the documentation project?  Duplicate key: M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)
SHFB: Warning WTOC0001: Duplicate key found in TOC.  This was unexpected.  Do you have the right framework version selected in the documentation project?  Duplicate key: M:Request.#ctor(System.Boolean,System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)
SHFB: Warning WTOC0001: Duplicate key found in TOC.  This was unexpected.  Do you have the right framework version selected in the documentation project?  Duplicate key: M:FluentValidatorExtensions.MoneyAmount``1(System.Boolean)
SHFB: Warning WTOC0001: Duplicate key found in TOC.  This was unexpected.  Do you have the right framework version selected in the documentation project?  Duplicate key: M:FluentValidatorExtensions.PositiveMoneyAmount``1(System.Boolean)
</plugIn>
```

When built with the **VS 2013** presentation the build fails with messages like

```
SHFB: Error BE0065: TransformComponent: [Overload:LoanQueryableRequest.#ctor] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiTypeMemberLists(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiMemberList(TopicTransformationCore transformation)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
```

**Comment by EWSoftware** [comment]
I'm unable to duplicate the issue with the snippets above. Can you provide a working example I can use to duplicate the issue?

**Comment by colsonab** [comment]
[ShfbBugs.zip](https://github.com/EWSoftware/SHFB/files/11537828/ShfbBugs.zip)
Hi Eric,

This is a simple AspNetCore (.NET Core 202) app straight from the project wizard with 2 classes of interest:

- **BugClass.cs**
- **BugExtensions.cs**

I left the build dirty so you could see the _toc.xml_ file which reports

    <topic id="T:ShfbBug.BugClass" file="78c16244-9932-155c-c9b2-f5a1a84ddb3b">
      <topic id="Overload:ShfbBug.BugClass.#ctor" file="250c94c3-4489-8a1a-d9ba-3cb0659281b0">
        <topic id="M:ShfbBug.BugClass.#ctor(System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="a2543cf3-9ddd-2e28-6040-e7e74ceeb729" />
        <topic id="M:ShfbBug.BugClass.#ctor(System.Collections.Generic.ICollection{System.Linq.Expressions.Expression`1},System.Void)" file="a2543cf3-9ddd-2e28-6040-e7e74ceeb729" />
      </topic>
      <topic id="Methods.T:ShfbBug.BugClass" file="91115598-4066-d37c-c5dc-9cc759b69999" />
    </topic>
    <topic id="T:ShfbBug.BugExtensions" file="16e0f593-554f-f4cc-f0e9-682c7c18a716">
      <topic id="Methods.T:ShfbBug.BugExtensions" file="9b78abe2-1678-6241-78cf-dacd0096dc38">
        <topic id="Overload:ShfbBug.BugExtensions.MyExtensionMethod" file="d89ce1f9-89af-0686-afdc-80a885565c6c">
          <topic id="M:ShfbBug.BugExtensions.MyExtensionMethod``1(System.Boolean)" file="3492ef6d-09c4-a921-55e0-c94f4d5cfe8f" />
          <topic id="M:ShfbBug.BugExtensions.MyExtensionMethod``1(System.Boolean)" file="3492ef6d-09c4-a921-55e0-c94f4d5cfe8f" />
        </topic>
      </topic>
    </topic>

I think the problem has to do with NuGet packages and nullables (in this case the package is **FluentValidation.AspNetCore 8.1.1**) compounded with registering assemblies with the **Assembly Binding Redirection** plugin as _"Ignore If Unresolved"_.

**Comment by EWSoftware** [comment]
Use the .NET Core/.NET Standard/.NET 5.0+ option for the SHFB Framework Version setting, remove the Assembly Binding Redirection plug-in, and use your project as the documentation source so that it can properly resolve the reference assemblies automatically.  Without that info, it doesn't have enough to create a proper match on the extension method parameters thus you get duplicate IDs.
