### ISSUE TITLE
When Build Assembler Verbosity is set to "All Messages", build fails with " Input string was not in a correct format."

### ISSUE THREAD

**Issue by ritchiecarroll** [EWSoftware/SHFB#999]
Tried this on several `.shfbproj` files and it was consistent - that said, most all of mine are configured the same way.

Here's an example if you can't replicate: 
https://github.com/gemstone/io/blob/master/src/DocGen/docgen.shfbproj

See log clip below for error stack trace. I imagine this will be an easy fix once you find the offending string format:

```
ResolveArtLinksComponent: Copying media files...
CopyFromIndexComponent: "reflection" in-memory cache entries used: 6 of 15.
CopyFromIndexComponent: "comments" in-memory cache entries used: 5 of 30.
    Last step completed in 00:00:07.0445
+Failed

-Failed


SHFB: Error BE0065: BUILD FAILED: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(MessageLevel level, String message)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.<BuildTopics>b__27_1()
   at System.Threading.Tasks.Task.Execute()

One or more errors occurred.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(MessageLevel level, String message)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.<BuildTopics>b__27_1()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by EWSoftware** [comment]
Are you using version 2022.10.15.0 or later?  A bug in the logging prior to that would fail with the above error.  I download the project above and it built without issue with the latest release with all messages logged.

**Comment by ritchiecarroll** [comment]
Good question - I thought I was on latest - but I changed machines., so maybe not.

What's a quick way to tell?

**Comment by ritchiecarroll** [comment]
Says 22.8.14.1 from installed programs

**Comment by ritchiecarroll** [comment]
Product version is 2022.8.14.1

**Comment by ritchiecarroll** [comment]
I will upgrade

**Comment by ritchiecarroll** [comment]
Yes, fixed in latest build. My apologies.
